version: '3.8'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: vocab_db
      MYSQL_USER: user
      MYSQL_PASSWORD: Pa55word
      MYSQL_ROOT_PASSWORD: Pa55word
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db_data: